import Head from "next/head";
import Image from "next/image";
import Link from "next/link";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div id="wrapper">
        <header>
          <nav>
            <Image src="" alt="Image" />
            <Link href="/events">Events</Link>
            <Link href="/">Home</Link>
            <Link href="/about">About us</Link>
          </nav>
        </header>
        <main>
          <Link href="#">
            <div>
              <Image src="" alt="Event image" />
              <h2>Events in London</h2>
              <p>
                Lorem ipsum dolor sit amet consectetur, adipisicing elit.
                Ratione totam praesentium amet deserunt minus quia eveniet
                dolorum maiores magni ut minima, repudiandae laudantium dolor
                necessitatibus numquam fugit error officiis quae.
              </p>
            </div>
          </Link>
          <Link href="#">
            <div>
              <Image src="" alt="Event image" />
              <h2>Events in San-Francisco</h2>
              <p>
                Lorem ipsum dolor sit amet consectetur, adipisicing elit.
                Ratione totam praesentium amet deserunt minus quia eveniet
                dolorum maiores magni ut minima, repudiandae laudantium dolor
                necessitatibus numquam fugit error officiis quae.
              </p>
            </div>
          </Link>
          <Link href="#">
            <div>
              <Image src="" alt="Event image" />
              <h2>Events in Barselona</h2>
              <p>
                Lorem ipsum dolor sit amet consectetur, adipisicing elit.
                Ratione totam praesentium amet deserunt minus quia eveniet
                dolorum maiores magni ut minima, repudiandae laudantium dolor
                necessitatibus numquam fugit error officiis quae.
              </p>
            </div>
          </Link>
        </main>
        <footer>Time to Code - A project of events.</footer>
      </div>
    </>
  );
}
